import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.image.BufferedImage;
/**
 *
 * @author marqu
 */
public class Video_Games extends javax.swing.JPanel {

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Video_Games.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Video_Games.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Video_Games.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Video_Games.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Video_Games game = new Video_Games();
                game.Game_Menu();

            //
            }
        });
     
    }
public void Game_Menu(){    
    jPanel1 = new javax.swing.JPanel(new BorderLayout());
    initComponents();
    game = this;
    frame = new JFrame();
    
    playstation = new PlayStation(game);
    xbox = new Xbox(game);
    frame.setSize(1200,900);
    game.setBackground(Color.LIGHT_GRAY);
    frame.getContentPane().add(game);
    
    frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    frame.pack();
    frame.setVisible(true);
    nintendo = new Nintendo(game);
    
}

public void switchToMainPanel() {
    initComponents();
    // Switch to the main frame
    frame.remove(nintendo);
    frame.remove(playstation);
    frame.remove(xbox);
    frame.setSize(1200,900);
    game.setBackground(Color.LIGHT_GRAY);
   frame.getContentPane().add(game);
   frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
   frame.pack();
   frame.setVisible(true);
    
    frame.revalidate();
    frame.repaint();
}

/**
 * This method is called from within the constructor to initialize the form.
 * WARNING: Do NOT modify this code. The content of this method is always
 * regenerated by the Form Editor.
 */
@SuppressWarnings("unchecked")
// <editor-fold defaultstate="collapsed" desc="Generated Code">                          
public void initComponents() {
    
   

    jButton1 = new javax.swing.JButton();
    jButton2 = new javax.swing.JButton();
    jButton3 = new javax.swing.JButton();
    jLabel1 = new javax.swing.JLabel();
    jButton4 = new javax.swing.JButton();
    

    

    //game.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    jButton2.setText("jButton1");

    jButton3.setText("jButton3");

    jLabel1.setText("Choose Your Category");

    jButton4.setText("Exit");

    // Load the image
    ImageIcon originalIcon1 = new ImageIcon("C:\\Users\\marqu\\Downloads\\Nintendo.png");
    Image originalImage1 = originalIcon1.getImage();

    // Resize the image
    int buttonWidth = 150;  // Set the desired button width
    int buttonHeight = 100; // Set the desired button height
    Image resizedImage = originalImage1.getScaledInstance(buttonWidth, buttonHeight, Image.SCALE_SMOOTH);

    // Create a new ImageIcon with the resized image
    ImageIcon resizedIcon1 = new ImageIcon(resizedImage);

    ImageIcon originalIcon2 = new ImageIcon("C:\\Playstation.jpg");
    Image originalImage2 = originalIcon2.getImage();

    Image resizedImage2 = originalImage2.getScaledInstance(buttonWidth, buttonHeight, Image.SCALE_SMOOTH);

    // Create a new ImageIcon with the resized image
    ImageIcon resizedIcon2 = new ImageIcon(resizedImage2);

    ImageIcon originalIcon3 = new ImageIcon("C:\\Xbox.jpg");
    Image originalImage3 = originalIcon3.getImage();

    Image resizedImage3 = originalImage3.getScaledInstance(buttonWidth, buttonHeight, Image.SCALE_SMOOTH);

    // Create a new ImageIcon with the resized image
    ImageIcon resizedIcon3 = new ImageIcon(resizedImage3);

    // Set the resized image to the button
    jButton1.setIcon(resizedIcon1);
    jButton2.setIcon(resizedIcon2);
    jButton3.setIcon(resizedIcon3);
    

    jButton4.addActionListener(new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent e) {
            System.exit(0);
        }
    });

    jButton3.addActionListener(new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent e) {
            // Code to be executed when jButton3 is clicked
            System.out.println("Button 3 clicked");

            frame.remove(game);
            frame.getContentPane().add(xbox);
            frame.repaint();
            frame.revalidate();
        }
    });

    jButton2.addActionListener(new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent e) {
            // Code to be executed when jButton3 is clicked
            System.out.println("Button 2 clicked");
            
            frame.remove(game);
            frame.getContentPane().add(playstation);
            frame.repaint();
            frame.revalidate();

        }
    });

    jButton1.addActionListener(new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent e) {
            // Code to be executed when jButton1 (Nintendo) is clicked
            System.out.println("Button 1 clicked");

            frame.remove(game);
            frame.getContentPane().add(nintendo);
            frame.repaint();
            frame.revalidate();
            
        }
    });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 650, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(86, 86, 86)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(48, 48, 48)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(43, 43, 43)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(177, 177, 177)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(188, 188, 188)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap(86, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 380, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(35, 35, 35)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(46, 46, 46)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(35, 35, 35)))
        );
    }// </editor-fold>                        
 

    // Variables declaration - do not modify                     
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private PlayStation playstation;
    private Video_Games game;
    private Xbox xbox;
    private Nintendo nintendo;
   // private Nintendo nintendo;
    private JFrame frame;  
}             

